/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Chat App Worker
 * OpenAPI spec version: 0.1.0
 */
export type ChatCallbackPayloadError = string | null;

/**
 * Payload sent from Worker back to App when task is complete.
 */
export interface ChatCallbackPayload {
	chat_id: string;
	response: string;
	status?: string;
	error?: ChatCallbackPayloadError;
}

export type ChatTriggerRequestMetadataAnyOf = { [key: string]: unknown };

export type ChatTriggerRequestMetadata = ChatTriggerRequestMetadataAnyOf | null;

/**
 * Payload sent from App to Worker to trigger an LLM task.
 */
export interface ChatTriggerRequest {
	chat_id: string;
	message: string;
	/**
	 * @minLength 1
	 * @maxLength 2083
	 */
	callback_url: string;
	metadata?: ChatTriggerRequestMetadata;
}

export interface HTTPValidationError {
	detail?: ValidationError[];
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
	loc: ValidationErrorLocItem[];
	msg: string;
	type: string;
}

/**
 * Endpoint for the App to trigger a new LLM task.
 * @summary Trigger Chat
 */
export type triggerChatChatTriggerPostResponse200 = {
	data: unknown;
	status: 200;
};

export type triggerChatChatTriggerPostResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type triggerChatChatTriggerPostResponseSuccess = triggerChatChatTriggerPostResponse200 & {
	headers: Headers;
};
export type triggerChatChatTriggerPostResponseError = triggerChatChatTriggerPostResponse422 & {
	headers: Headers;
};

export type triggerChatChatTriggerPostResponse =
	| triggerChatChatTriggerPostResponseSuccess
	| triggerChatChatTriggerPostResponseError;

export const getTriggerChatChatTriggerPostUrl = () => {
	return `http://localhost:8000/chat/trigger`;
};

export const triggerChatChatTriggerPost = async (
	chatTriggerRequest: ChatTriggerRequest,
	options?: RequestInit
): Promise<triggerChatChatTriggerPostResponse> => {
	const res = await fetch(getTriggerChatChatTriggerPostUrl(), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		body: JSON.stringify(chatTriggerRequest)
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: triggerChatChatTriggerPostResponse['data'] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as triggerChatChatTriggerPostResponse;
};

/**
 * Endpoint used ONLY for generating the callback payload type in the frontend SDK.
 * @summary Callback Schema Discovery
 */
export type callbackSchemaDiscoveryChatCallbackSchemaDiscoveryPostResponse200 = {
	data: unknown;
	status: 200;
};

export type callbackSchemaDiscoveryChatCallbackSchemaDiscoveryPostResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type callbackSchemaDiscoveryChatCallbackSchemaDiscoveryPostResponseSuccess =
	callbackSchemaDiscoveryChatCallbackSchemaDiscoveryPostResponse200 & {
		headers: Headers;
	};
export type callbackSchemaDiscoveryChatCallbackSchemaDiscoveryPostResponseError =
	callbackSchemaDiscoveryChatCallbackSchemaDiscoveryPostResponse422 & {
		headers: Headers;
	};

export type callbackSchemaDiscoveryChatCallbackSchemaDiscoveryPostResponse =
	| callbackSchemaDiscoveryChatCallbackSchemaDiscoveryPostResponseSuccess
	| callbackSchemaDiscoveryChatCallbackSchemaDiscoveryPostResponseError;

export const getCallbackSchemaDiscoveryChatCallbackSchemaDiscoveryPostUrl = () => {
	return `http://localhost:8000/chat/callback-schema-discovery`;
};

export const callbackSchemaDiscoveryChatCallbackSchemaDiscoveryPost = async (
	chatCallbackPayload: ChatCallbackPayload,
	options?: RequestInit
): Promise<callbackSchemaDiscoveryChatCallbackSchemaDiscoveryPostResponse> => {
	const res = await fetch(getCallbackSchemaDiscoveryChatCallbackSchemaDiscoveryPostUrl(), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		body: JSON.stringify(chatCallbackPayload)
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: callbackSchemaDiscoveryChatCallbackSchemaDiscoveryPostResponse['data'] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers
	} as callbackSchemaDiscoveryChatCallbackSchemaDiscoveryPostResponse;
};

/**
 * @summary Read Root
 */
export type readRootGetResponse200 = {
	data: unknown;
	status: 200;
};

export type readRootGetResponseSuccess = readRootGetResponse200 & {
	headers: Headers;
};
export type readRootGetResponse = readRootGetResponseSuccess;

export const getReadRootGetUrl = () => {
	return `http://localhost:8000/`;
};

export const readRootGet = async (options?: RequestInit): Promise<readRootGetResponse> => {
	const res = await fetch(getReadRootGetUrl(), {
		...options,
		method: 'GET'
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: readRootGetResponse['data'] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as readRootGetResponse;
};
