/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Chat App Worker
 * OpenAPI spec version: 0.1.0
 */
export type ChatCallbackPayloadError = string | null;

/**
 * Payload sent from Worker back to App when task is complete.
 */
export interface ChatCallbackPayload {
	chatId: string;
	response: string;
	status?: string;
	error?: ChatCallbackPayloadError;
}

export type ChatTriggerRequestProvider = string | null;

export type ChatTriggerRequestModel = string | null;

export type ChatTriggerRequestMetadataAnyOf = { [key: string]: unknown };

export type ChatTriggerRequestMetadata = ChatTriggerRequestMetadataAnyOf | null;

/**
 * Payload sent from App to Worker to trigger an LLM task.
 */
export interface ChatTriggerRequest {
	chat_id: string;
	message: string;
	/**
	 * @minLength 1
	 * @maxLength 2083
	 */
	callback_url: string;
	provider?: ChatTriggerRequestProvider;
	model?: ChatTriggerRequestModel;
	metadata?: ChatTriggerRequestMetadata;
}

export interface HTTPValidationError {
	detail?: ValidationError[];
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
	loc: ValidationErrorLocItem[];
	msg: string;
	type: string;
}

/**
 * Endpoint for the App to trigger a new LLM task.
 * @summary Trigger Chat
 */
export type triggerChatResponse200 = {
	data: unknown;
	status: 200;
};

export type triggerChatResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type triggerChatResponseSuccess = triggerChatResponse200 & {
	headers: Headers;
};
export type triggerChatResponseError = triggerChatResponse422 & {
	headers: Headers;
};

export type triggerChatResponse = triggerChatResponseSuccess | triggerChatResponseError;

export const getTriggerChatUrl = () => {
	return `http://localhost:8000/chats/trigger`;
};

export const triggerChat = async (
	chatTriggerRequest: ChatTriggerRequest,
	options?: RequestInit
): Promise<triggerChatResponse> => {
	const res = await fetch(getTriggerChatUrl(), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		body: JSON.stringify(chatTriggerRequest)
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: triggerChatResponse['data'] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as triggerChatResponse;
};

/**
 * Endpoint used ONLY for generating the callback payload type in the frontend SDK.
 * @summary Callback Schema Discovery
 */
export type callbackSchemaDiscoveryResponse200 = {
	data: unknown;
	status: 200;
};

export type callbackSchemaDiscoveryResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type callbackSchemaDiscoveryResponseSuccess = callbackSchemaDiscoveryResponse200 & {
	headers: Headers;
};
export type callbackSchemaDiscoveryResponseError = callbackSchemaDiscoveryResponse422 & {
	headers: Headers;
};

export type callbackSchemaDiscoveryResponse =
	| callbackSchemaDiscoveryResponseSuccess
	| callbackSchemaDiscoveryResponseError;

export const getCallbackSchemaDiscoveryUrl = () => {
	return `http://localhost:8000/chats/callback-schema-discovery`;
};

export const callbackSchemaDiscovery = async (
	chatCallbackPayload: ChatCallbackPayload,
	options?: RequestInit
): Promise<callbackSchemaDiscoveryResponse> => {
	const res = await fetch(getCallbackSchemaDiscoveryUrl(), {
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		body: JSON.stringify(chatCallbackPayload)
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: callbackSchemaDiscoveryResponse['data'] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as callbackSchemaDiscoveryResponse;
};

/**
 * @summary Read Root
 */
export type readRootGetResponse200 = {
	data: unknown;
	status: 200;
};

export type readRootGetResponseSuccess = readRootGetResponse200 & {
	headers: Headers;
};
export type readRootGetResponse = readRootGetResponseSuccess;

export const getReadRootGetUrl = () => {
	return `http://localhost:8000/`;
};

export const readRootGet = async (options?: RequestInit): Promise<readRootGetResponse> => {
	const res = await fetch(getReadRootGetUrl(), {
		...options,
		method: 'GET'
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: readRootGetResponse['data'] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as readRootGetResponse;
};
